package com.bruce.designer.model;


public class AlbumSlide extends AlbumBase{

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_slide.id
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_slide.title
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    private String title;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_slide.remark
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    private String remark;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_slide.album_id
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    private Integer albumId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_slide.user_id
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    private Integer userId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_slide.is_cover
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    private Short isCover;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_slide.slide_large_img
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    private String slideLargeImg;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_slide.slide_medium_img
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    private String slideMediumImg;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_slide.slide_small_img
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    private String slideSmallImg;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_slide.status
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    private Short status;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_slide.create_time
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    private long createTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_album_slide.update_time
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    private long updateTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_slide.id
     * @return  the value of tb_album_slide.id
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_slide.id
     * @param id  the value for tb_album_slide.id
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_slide.title
     * @return  the value of tb_album_slide.title
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_slide.title
     * @param title  the value for tb_album_slide.title
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_slide.remark
     * @return  the value of tb_album_slide.remark
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_slide.remark
     * @param remark  the value for tb_album_slide.remark
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_slide.album_id
     * @return  the value of tb_album_slide.album_id
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    public Integer getAlbumId() {
        return albumId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_slide.album_id
     * @param albumId  the value for tb_album_slide.album_id
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    public void setAlbumId(Integer albumId) {
        this.albumId = albumId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_slide.user_id
     * @return  the value of tb_album_slide.user_id
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_slide.user_id
     * @param userId  the value for tb_album_slide.user_id
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_slide.is_cover
     * @return  the value of tb_album_slide.is_cover
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    public Short getIsCover() {
        return isCover;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_slide.is_cover
     * @param isCover  the value for tb_album_slide.is_cover
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    public void setIsCover(Short isCover) {
        this.isCover = isCover;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_slide.slide_large_img
     * @return  the value of tb_album_slide.slide_large_img
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    public String getSlideLargeImg() {
        return slideLargeImg;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_slide.slide_large_img
     * @param slideLargeImg  the value for tb_album_slide.slide_large_img
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    public void setSlideLargeImg(String slideLargeImg) {
        this.slideLargeImg = slideLargeImg;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_slide.slide_medium_img
     * @return  the value of tb_album_slide.slide_medium_img
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    public String getSlideMediumImg() {
        return slideMediumImg;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_slide.slide_medium_img
     * @param slideMediumImg  the value for tb_album_slide.slide_medium_img
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    public void setSlideMediumImg(String slideMediumImg) {
        this.slideMediumImg = slideMediumImg;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_slide.slide_small_img
     * @return  the value of tb_album_slide.slide_small_img
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    public String getSlideSmallImg() {
        return slideSmallImg;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_slide.slide_small_img
     * @param slideSmallImg  the value for tb_album_slide.slide_small_img
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    public void setSlideSmallImg(String slideSmallImg) {
        this.slideSmallImg = slideSmallImg;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_slide.status
     * @return  the value of tb_album_slide.status
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_slide.status
     * @param status  the value for tb_album_slide.status
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_slide.create_time
     * @return  the value of tb_album_slide.create_time
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    public long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_slide.create_time
     * @param createTime  the value for tb_album_slide.create_time
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    public void setCreateTime(long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_album_slide.update_time
     * @return  the value of tb_album_slide.update_time
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    public long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_album_slide.update_time
     * @param updateTime  the value for tb_album_slide.update_time
     * @mbggenerated  Tue Oct 08 19:47:44 CST 2013
     */
    public void setUpdateTime(long updateTime) {
        this.updateTime = updateTime;
    }
}