package com.bruce.designer.model;

public class Comment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_comment.id
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_comment.title
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_comment.comment
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	private String comment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_comment.from_id
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	private Integer fromId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_comment.to_id
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	private Integer toId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_comment.designer_id
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	private Integer designerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_comment.album_id
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	private Integer albumId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_comment.album_slide_id
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	private Integer albumSlideId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_comment.user_head_img
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	private String userHeadImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_comment.nickname
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	private String nickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_comment.status
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_comment.create_time
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	private long createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_comment.update_time
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	private long updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.id
	 * @return  the value of tb_comment.id
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.id
	 * @param id  the value for tb_comment.id
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.title
	 * @return  the value of tb_comment.title
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.title
	 * @param title  the value for tb_comment.title
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.comment
	 * @return  the value of tb_comment.comment
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.comment
	 * @param comment  the value for tb_comment.comment
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.from_id
	 * @return  the value of tb_comment.from_id
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	public Integer getFromId() {
		return fromId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.from_id
	 * @param fromId  the value for tb_comment.from_id
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	public void setFromId(Integer fromId) {
		this.fromId = fromId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.to_id
	 * @return  the value of tb_comment.to_id
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	public Integer getToId() {
		return toId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.to_id
	 * @param toId  the value for tb_comment.to_id
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	public void setToId(Integer toId) {
		this.toId = toId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.designer_id
	 * @return  the value of tb_comment.designer_id
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	public Integer getDesignerId() {
		return designerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.designer_id
	 * @param designerId  the value for tb_comment.designer_id
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	public void setDesignerId(Integer designerId) {
		this.designerId = designerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.album_id
	 * @return  the value of tb_comment.album_id
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	public Integer getAlbumId() {
		return albumId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.album_id
	 * @param albumId  the value for tb_comment.album_id
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	public void setAlbumId(Integer albumId) {
		this.albumId = albumId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.album_slide_id
	 * @return  the value of tb_comment.album_slide_id
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	public Integer getAlbumSlideId() {
		return albumSlideId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.album_slide_id
	 * @param albumSlideId  the value for tb_comment.album_slide_id
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	public void setAlbumSlideId(Integer albumSlideId) {
		this.albumSlideId = albumSlideId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.user_head_img
	 * @return  the value of tb_comment.user_head_img
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	public String getUserHeadImg() {
		return userHeadImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.user_head_img
	 * @param userHeadImg  the value for tb_comment.user_head_img
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	public void setUserHeadImg(String userHeadImg) {
		this.userHeadImg = userHeadImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.nickname
	 * @return  the value of tb_comment.nickname
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.nickname
	 * @param nickname  the value for tb_comment.nickname
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.status
	 * @return  the value of tb_comment.status
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.status
	 * @param status  the value for tb_comment.status
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.create_time
	 * @return  the value of tb_comment.create_time
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	public long getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.create_time
	 * @param createTime  the value for tb_comment.create_time
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	public void setCreateTime(long createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_comment.update_time
	 * @return  the value of tb_comment.update_time
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	public long getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_comment.update_time
	 * @param updateTime  the value for tb_comment.update_time
	 * @mbggenerated  Mon Sep 30 00:16:22 CST 2013
	 */
	public void setUpdateTime(long updateTime) {
		this.updateTime = updateTime;
	}
}