package com.bruce.designer.model;

public class Message extends MessageBase{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_message.id
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_message.message
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	private String message;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_message.message_type
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	private Integer messageType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_message.source_type
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	private Short sourceType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_message.source_id
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	private Long sourceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_message.source_desc
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	private String sourceDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_message.from_id
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	private Integer fromId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_message.to_id
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	private Integer toId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_message.unread
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	private Short unread;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_message.status
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_message.create_time
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	private long createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_message.update_time
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	private long updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_message.id
	 * @return  the value of tb_message.id
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_message.id
	 * @param id  the value for tb_message.id
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_message.message
	 * @return  the value of tb_message.message
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	public String getMessage() {
		return message;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_message.message
	 * @param message  the value for tb_message.message
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	public void setMessage(String message) {
		this.message = message;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_message.message_type
	 * @return  the value of tb_message.message_type
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	public Integer getMessageType() {
		return messageType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_message.message_type
	 * @param messageType  the value for tb_message.message_type
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	public void setMessageType(Integer messageType) {
		this.messageType = messageType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_message.source_type
	 * @return  the value of tb_message.source_type
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	public Short getSourceType() {
		return sourceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_message.source_type
	 * @param sourceType  the value for tb_message.source_type
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	public void setSourceType(Short sourceType) {
		this.sourceType = sourceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_message.source_id
	 * @return  the value of tb_message.source_id
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	public Long getSourceId() {
		return sourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_message.source_id
	 * @param sourceId  the value for tb_message.source_id
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	public void setSourceId(Long sourceId) {
		this.sourceId = sourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_message.source_desc
	 * @return  the value of tb_message.source_desc
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	public String getSourceDesc() {
		return sourceDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_message.source_desc
	 * @param sourceDesc  the value for tb_message.source_desc
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	public void setSourceDesc(String sourceDesc) {
		this.sourceDesc = sourceDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_message.from_id
	 * @return  the value of tb_message.from_id
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	public Integer getFromId() {
		return fromId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_message.from_id
	 * @param fromId  the value for tb_message.from_id
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	public void setFromId(Integer fromId) {
		this.fromId = fromId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_message.to_id
	 * @return  the value of tb_message.to_id
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	public Integer getToId() {
		return toId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_message.to_id
	 * @param toId  the value for tb_message.to_id
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	public void setToId(Integer toId) {
		this.toId = toId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_message.unread
	 * @return  the value of tb_message.unread
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	public Short getUnread() {
		return unread;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_message.unread
	 * @param unread  the value for tb_message.unread
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	public void setUnread(Short unread) {
		this.unread = unread;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_message.status
	 * @return  the value of tb_message.status
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_message.status
	 * @param status  the value for tb_message.status
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_message.create_time
	 * @return  the value of tb_message.create_time
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	public long getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_message.create_time
	 * @param createTime  the value for tb_message.create_time
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	public void setCreateTime(long createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_message.update_time
	 * @return  the value of tb_message.update_time
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	public long getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_message.update_time
	 * @param updateTime  the value for tb_message.update_time
	 * @mbggenerated  Thu Aug 21 19:45:26 CST 2014
	 */
	public void setUpdateTime(long updateTime) {
		this.updateTime = updateTime;
	}
}