package com.bruce.designer.model;

public class UserFollow {
    
    private User followUser;
    
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_follow.id
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_follow.user_id
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    private Integer userId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_follow.follow_id
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    private Integer followId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_follow.create_time
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    private long createTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_follow.update_time
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    private long updateTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_follow.id
     * @return  the value of tb_user_follow.id
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_follow.id
     * @param id  the value for tb_user_follow.id
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_follow.user_id
     * @return  the value of tb_user_follow.user_id
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_follow.user_id
     * @param userId  the value for tb_user_follow.user_id
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_follow.follow_id
     * @return  the value of tb_user_follow.follow_id
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    public Integer getFollowId() {
        return followId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_follow.follow_id
     * @param followId  the value for tb_user_follow.follow_id
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    public void setFollowId(Integer followId) {
        this.followId = followId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_follow.create_time
     * @return  the value of tb_user_follow.create_time
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    public long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_follow.create_time
     * @param createTime  the value for tb_user_follow.create_time
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    public void setCreateTime(long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_follow.update_time
     * @return  the value of tb_user_follow.update_time
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    public long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_follow.update_time
     * @param updateTime  the value for tb_user_follow.update_time
     * @mbggenerated  Wed Oct 09 14:27:12 CST 2013
     */
    public void setUpdateTime(long updateTime) {
        this.updateTime = updateTime;
    }

    public User getFollowUser() {
        return followUser;
    }

    public void setFollowUser(User followUser) {
        this.followUser = followUser;
    }
    
    
}